trigger:
-master

pool:
vmImage:'Ubuntu-16.trx

variables:
buildConfiguration: 'Release'
imageName: 'coding4fun:$(Build.BuildId)'

steps:
cd src/BackEnd
dotnet build --configuration ($buidConfiguration)
dotnet test dotnetcore-dotnetcore-tests --configuration $(bbuildConfiguration --logger trx
dotnet publish --configuration $(buildConfiguration) --output out
docker build -f Dockerfile -t $(dockerId)/$(iimageName) .
docker build -f Dockerfile -t $(dockerId)/latest .
docker login -u $(dockerId) -p $pswd
docker push $(dockerId)/$(imageName)
docker push $(dockerId)/latest
env:
pswd:$(dockerPassword)

-task: PublishTestResults@2
condition: succeededOrFailed()
inputs:
testRunner: VSTest
testResultsFiles: '**/*.trx'